// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9krVPPQd8mejmdr4TBwhgmq6B8gRcVgo',
    appId: '1:866805122672:web:31bbeeebc7cf30d39896b5',
    messagingSenderId: '866805122672',
    projectId: 'cityconnect-8b651',
    authDomain: 'cityconnect-8b651.firebaseapp.com',
    storageBucket: 'cityconnect-8b651.firebasestorage.app',
    measurementId: 'G-7J72XBHS88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3kdn6-0wuqGhhq2-zQDyJwtnnpvcim14',
    appId: '1:866805122672:android:3589dbd3fb3bd4c09896b5',
    messagingSenderId: '866805122672',
    projectId: 'cityconnect-8b651',
    storageBucket: 'cityconnect-8b651.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASwztswFH-wG5oFgcWxzU6XD-t_TXXziQ',
    appId: '1:866805122672:ios:ae4835984c3ca45c9896b5',
    messagingSenderId: '866805122672',
    projectId: 'cityconnect-8b651',
    storageBucket: 'cityconnect-8b651.firebasestorage.app',
    iosBundleId: 'com.example.cityConnect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASwztswFH-wG5oFgcWxzU6XD-t_TXXziQ',
    appId: '1:866805122672:ios:ae4835984c3ca45c9896b5',
    messagingSenderId: '866805122672',
    projectId: 'cityconnect-8b651',
    storageBucket: 'cityconnect-8b651.firebasestorage.app',
    iosBundleId: 'com.example.cityConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9krVPPQd8mejmdr4TBwhgmq6B8gRcVgo',
    appId: '1:866805122672:web:7f5667be0f2a5dd89896b5',
    messagingSenderId: '866805122672',
    projectId: 'cityconnect-8b651',
    authDomain: 'cityconnect-8b651.firebaseapp.com',
    storageBucket: 'cityconnect-8b651.firebasestorage.app',
    measurementId: 'G-CGKV31XPF9',
  );
}
